apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: exoapp-cockroachdb-privileged-scc
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: exoapp-cockroachdb
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:privileged
  apiGroup: rbac.authorization.k8s.io